---
# tasks file for apt_repository

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: manage repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    validate_certs: no
  loop: "{{ apt_repositories }}"
  loop_control:
    label: "{{ item.repo }}"
  when:
    - apt_repositories is defined
