---
# tasks file for apt_repository

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: manage repository
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    validate_certs: no
  loop: "{{ apt_repositories }}"
  loop_control:
    label: "{{ item.repo }}"
  when:
    - apt_repositories is defined
