---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-apt_repository
      apt_repositories:
        - repo: "deb https://dl.yarnpkg.com/debian/ stable main"
