---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: ansible-role-apt_repository
      apt_repositories:
        - repo: ppa:videolan/master-daily

  post_tasks:
    - name: install a test package
      ansible.builtin.package:
        name: vlc
